name: Build and Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/394545247701/locations/global/workloadIdentityPools/github-pool/providers/github-actions'
          service_account: 'github-actions-deployer@travel-agent-465305.iam.gserviceaccount.com'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Authorize Docker push
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build and Push Web Container
        run: |
          docker build -t us-central1-docker.pkg.dev/travel-agent-465305/travel-agent/app-web:latest -f Dockerfile.web .
          docker push us-central1-docker.pkg.dev/travel-agent-465305/travel-agent/app-web:latest

      - name: Deploy Web to Cloud Run (no traffic)
        run: |
          gcloud run deploy ai-travel-agent-web \
            --image us-central1-docker.pkg.dev/travel-agent-465305/travel-agent/app-web:latest \
            --region us-central1 \
            --platform managed \
            --allow-unauthenticated \
            --vpc-connector cloud-run-connector \
            --no-traffic \
            --set-secrets=REDIS_URL=REDIS_URL:latest,TWILIO_ACCOUNT_SID=TWILIO_ACCOUNT_SID:latest,TWILIO_AUTH_TOKEN=TWILIO_AUTH_TOKEN:latest,IO_API_KEY=IO_API_KEY:latest,AMADEUS_CLIENT_ID=AMADEUS_CLIENT_ID:latest,AMADEUS_CLIENT_SECRET=AMADEUS_CLIENT_SECRET:latest,STRIPE_PUBLISHABLE_KEY=STRIPE_PUBLISHABLE_KEY:latest,STRIPE_SECRET_KEY=STRIPE_SECRET_KEY:latest,STRIPE_WEBHOOK_SECRET=STRIPE_WEBHOOK_SECRET:latest,TELEGRAM_BOT_TOKEN=TELEGRAM_BOT_TOKEN:latest

      - name: Route traffic to new Web revision
        run: |
          gcloud run services update-traffic ai-travel-agent-web \
            --to-latest \
            --region us-central1
